'use strict';
(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],data=window.O10_DATA,models=window.O10_MODELS,rad=Math.PI/180;
const state={tab:'joint',q:[0,0,76.65523548756507,0],yaw:.4,pitch:-1.05,zoom:1,exploded:false,playing:false,progress:0,phase:0};
const I=()=>[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],mul=(a,b)=>Array.from({length:16},(_,k)=>[0,1,2,3].reduce((s,i)=>s+a[Math.floor(k/4)*4+i]*b[i*4+k%4],0));
function R(axis,a){const m=I(),c=Math.cos(a),s=Math.sin(a);if(axis==='x'){m[5]=c;m[6]=-s;m[9]=s;m[10]=c;}else if(axis==='y'){m[0]=c;m[2]=s;m[8]=-s;m[10]=c;}else{m[0]=c;m[1]=-s;m[4]=s;m[5]=c;}return m;}
function T(x,y,z){const m=I();m[3]=x;m[7]=y;m[11]=z;return m;}
const color=h=>[1,3,5].map(i=>parseInt(h.slice(i,i+2),16)/255),column=m=>new Float32Array(Array.from({length:16},(_,i)=>m[(i%4)*4+Math.floor(i/4)]));
const canvas=$('#model'),gl=canvas.getContext('webgl',{antialias:true,preserveDrawingBuffer:true}),cache={};let loc,program;
if(gl){const shader=(type,src)=>{const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;};program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,'attribute vec3 p;attribute vec3 n;uniform mat4 M;uniform vec2 scale;varying vec3 normal;void main(){vec4 v=M*vec4(p,1.);normal=normalize((M*vec4(n,0.)).xyz);gl_Position=vec4(v.x*scale.x,v.y*scale.y,-v.z/1000.,1.);}'));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,'precision mediump float;varying vec3 normal;uniform vec3 color;void main(){float light=.35+.65*max(0.,dot(normalize(normal),normalize(vec3(-.4,.7,1.))));gl_FragColor=vec4(color*light,1.);}'));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);loc={p:gl.getAttribLocation(program,'p'),n:gl.getAttribLocation(program,'n'),M:gl.getUniformLocation(program,'M'),scale:gl.getUniformLocation(program,'scale'),color:gl.getUniformLocation(program,'color')};gl.enable(gl.DEPTH_TEST);}else $('#webgl-error').hidden=false;
function mesh(key){if(cache[key])return cache[key];const o=models[key],a=[];for(const f of o.f){const [p,q,r]=f.map(i=>o.v[i]),u=q.map((x,i)=>x-p[i]),v=r.map((x,i)=>x-p[i]);let n=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]],l=Math.hypot(...n)||1;n=n.map(x=>x/l);for(const p0 of [p,q,r])a.push(...p0,...n);}const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(a),gl.STATIC_DRAW);return cache[key]={b,count:a.length/6};}
function coreFrames(){const q=state.q.map((v,i)=>(v+data.mapping.paths[0].zero_offsets_deg[i])*rad),p=R('z',q[0]),a=mul(p,R('x',q[1])),b=mul(a,R('y',q[2]));return {P:I(),C01:p,ring:a,C02:b,D:mul(mul(b,R('z',q[3])),R('x',Math.PI))};}
function scene(){const e=state.exploded?1:0,items=[];let center=[0,0,0],radius=46;
 if(state.tab==='joint'){const frames=coreFrames();for(const o of data.core){if(!$('#covers').checked&&o.name.includes('case_'))continue;let d=[0,0,0];if(e){if(o.role==='C01')d=[0,0,-8];else if(o.role==='C02')d=[0,0,8];else if(o.name==='C14')d=[0,0,-4];else if(o.name==='C15')d=[0,0,4];else if(o.name.includes('_-1_'))d=o.name.startsWith('C01')?[-5,0,0]:[0,-5,0];else if(o.name.includes('_+1_'))d=o.name.startsWith('C01')?[5,0,0]:[0,5,0];else if(o.name.includes('case_minus'))d=[0,-6,0];else if(o.name.includes('case_plus'))d=[0,6,0];}items.push({...o,M:mul(frames[o.role],T(...d))});}}
 else if(state.tab==='bench'){center=[43,0,7];radius=72;for(const [i,o] of data.bench.entries()){let gap=e*Math.max(0,i-1)*2.4;if(o.name==='aluminium_base')gap=-6*e;if(o.name.includes('rear')||o.name.includes('nut'))gap=-6*e;items.push({...o,M:T(0,0,gap)});}for(const o of data.benchIllustrations||[])items.push({...o,M:I()});}
 else if(state.tab==='wire'){center=[0,0,-30];radius=16;for(const o of data.wire){let m=I();if(o.name==='existing_rotor')m=mul(T(e*10,0,0),R('z',state.phase*2*Math.PI));if(o.name==='catalogue_rotor_tip')m=R('z',state.phase*2*Math.PI);if(o.name==='proposed_sleeve')m=T(-e*10,0,0);items.push({...o,M:m});}}
 else if(state.tab==='shoulder'){const char=$('#character').value,i=+$('#body-pose').value,s=data.states[char][i],result=data.results.clav_cases.find(r=>r.character===char&&r.pose===s.pose),bad=new Set(result.findings.flatMap(x=>x.pair));for(const o of s.objects){items.push({key:data.shoulder[o.library],name:o.id,color:bad.has(o.id)?'#b34e38':o.library==='clav_input'?'#b27e4d':o.library==='clav_ring'?'#7892aa':o.library==='clav_output'?'#638b73':o.id.startsWith('TUT')?'#b6bcb1':'#8b9b9e',M:o.frame.flat()});}center=[-25,0,335];radius=125;}
 return {items,center,radius};}
function draw(){if(!gl||state.tab==='evidence')return;const w=canvas.clientWidth,h=canvas.clientHeight,dpr=Math.min(devicePixelRatio||1,2);canvas.width=w*dpr;canvas.height=h*dpr;gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(.894,.914,.866,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const {items,center,radius}=scene(),scale=Math.min(w,h)*.46/radius*state.zoom;let view=mul(R('x',state.pitch),R('z',state.yaw));if(state.tab==='bench')view=mul(R('y',.3),view);if(state.tab==='shoulder')view=mul([0,-1,0,0,0,0,1,0,-1,0,0,0,0,0,0,1],mul(R('x',state.pitch+.95),R('z',state.yaw)));view=mul(view,T(...center.map(x=>-x)));gl.uniform2f(loc.scale,2*scale/w,2*scale/h);for(const p of items){const o=mesh(p.key);gl.bindBuffer(gl.ARRAY_BUFFER,o.b);gl.enableVertexAttribArray(loc.p);gl.vertexAttribPointer(loc.p,3,gl.FLOAT,false,24,0);gl.enableVertexAttribArray(loc.n);gl.vertexAttribPointer(loc.n,3,gl.FLOAT,false,24,12);gl.uniformMatrix4fv(loc.M,false,column(mul(view,p.M)));gl.uniform3fv(loc.color,color(p.color));gl.drawArrays(gl.TRIANGLES,0,o.count);}}
function pause(){state.playing=false;$('#play').textContent='播放演示';$('#play').setAttribute('aria-pressed','false');}
function update(){const q=state.q;$$('[data-axis]').forEach(s=>{const i=+s.dataset.axis;s.value=q[i];$('#q'+i).textContent=q[i].toFixed(1)+'°';});const inside=Math.abs(q[1])<=28&&Math.abs(q[2])<=98,b=$('#joint-status');$('#sliders').hidden=!inside;b.className='status'+(inside?'':' bad');b.textContent=inside?'两叉架位于连续验证区：名义间隙下界 ≥0.6 mm。完整接头通过的是 204 个目标端点；这里任意拖动后的整接头状态尚无连续通过结论。':'范围外反例 α=75°、β=75°：此视图绕过实体限位以展示相撞位置；不代表真实关节可被操作到这里。';const char=$('#character').value,i=+$('#body-pose').value,s=data.states[char][i],r=data.results.clav_cases.find(x=>x.character===char&&x.pose===s.pose),a=$('#body-status');a.className='status '+(r.findings.length?'bad':'amber');a.textContent=r.findings.length?'此端点发现 '+r.findings.length+' 对实体穿插。保留失败，未删除这个姿势目标。':'此端点所检查模块间未发现体积穿插；共同总装仍未通过。';const mass=+$('#mass').value;$('#mass-value').textContent=mass+' g';$('#torque').textContent=mass+' g × 100 mm → '+(mass*9.80665e-4).toFixed(3)+' N·m';draw();}
function tab(name){pause();state.tab=name;state.exploded=name==='wire';$('#explode').checked=state.exploded;$$('[data-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.tab===name)));$$('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==name);$('#workspace').hidden=name==='evidence';$('#evidence').hidden=name!=='evidence';$('#cover-control').hidden=name!=='joint';$('#explode').parentElement.hidden=name==='shoulder';$('#play').hidden=name==='shoulder';state.yaw=['shoulder','bench'].includes(name)?0:.4;state.pitch=name==='shoulder'?-.95:name==='bench'?-.08:-1.05;state.zoom=1;$('#scene-label').textContent={joint:'承力轴、碟簧与端面摩擦',shoulder:'双侧胸肩 · 保留失败端点',wire:'微型滑环 · 目录尺寸包络',bench:'独立摩擦小样 · 装配示意'}[name]||'';$('#caption').textContent=name==='bench'?'挂重与细线是加载方向示意，未纳入结构验收。长臂没有因动画而获得保持力。':name==='wire'?'按厂家目录外形建模；不是厂家内部 CAD。旋转动画不代表通信可靠性已验证。':'拖动旋转，滚轮缩放。拆开视图用于识别零件，不代表完整装配路径已经验证。';update();}
$$('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));$('#reset').onclick=()=>{state.yaw=['shoulder','bench'].includes(state.tab)?0:.4;state.pitch=state.tab==='shoulder'?-.95:state.tab==='bench'?-.08:-1.05;state.zoom=1;draw();};$('#explode').onchange=e=>{pause();state.exploded=e.target.checked;draw();};$('#covers').onchange=draw;$('#mass').oninput=update;$('#character').onchange=update;$('#body-pose').onchange=update;
let drag=null;canvas.onpointerdown=e=>{drag=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(drag){state.yaw+=(e.clientX-drag[0])*.007;state.pitch+=(e.clientY-drag[1])*.007;drag=[e.clientX,e.clientY];draw();}};canvas.onpointerup=canvas.onpointercancel=()=>drag=null;canvas.onwheel=e=>{e.preventDefault();state.zoom=Math.max(.5,Math.min(3,state.zoom*Math.exp(-e.deltaY*.001)));draw();};canvas.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();if(e.key==='ArrowLeft')state.yaw-=.1;if(e.key==='ArrowRight')state.yaw+=.1;if(e.key==='ArrowUp')state.pitch+=.1;if(e.key==='ArrowDown')state.pitch-=.1;draw();};
const labels=['近端转动 φ','第一弯折 α','第二弯折 β','远端转动 ψ'],limits=[[-170,50],[-28,28],[-98,98],[-95,105]];$('#sliders').innerHTML=labels.map((n,i)=>'<label>'+n+'<output id="q'+i+'"></output><input aria-label="'+n+'" data-axis="'+i+'" type="range" min="'+limits[i][0]+'" max="'+limits[i][1]+'" step=".1"></label>').join('');$$('[data-axis]').forEach(s=>s.oninput=()=>{pause();state.q[+s.dataset.axis]=+s.value;$('#pose').value='-1';update();});
function poseName(s){const named={neutral:'中立姿势',arms_forward:'双臂前伸',arms_overhead:'双臂举过头顶',arms_side:'双臂侧抬',hands_on_hips:'双手叉腰',arms_crossed:'双臂交叉',forehead:'手靠前额',palms_turn:'翻转手掌',arms_crossed_asymmetric_candidate:'双臂一高一低交叉'};if(named[s])return named[s];let m=s.match(/^([a-z]+)_[lr]\.([a-z]+)_(-?\d+)$/);if(m)return ({clavicle:'锁骨',upperarm:'上臂',elbow:'肘',forearm:'前臂',hand:'手腕'}[m[1]]||m[1])+({protract:'前后移',elevate:'抬升',flex:'屈伸',abduct:'外展',twist:'转动',deviate:'侧偏'}[m[2]]||m[2])+' '+m[3]+'°';return s.replace('back_reach_','向后伸手 ');}
$('#pose').innerHTML='<option value="-1">手动查看</option>'+data.mapping.paths.map((p,i)=>'<option value="'+i+'">'+poseName(p.pose)+'</option>').join('');$('#pose').value='0';$('#pose').onchange=()=>{pause();if(+$('#pose').value>=0)state.q=[...data.mapping.paths[+$('#pose').value].angles_deg.at(-1)];update();};$('#straight').onclick=()=>{pause();state.q=[0,0,0,0];$('#pose').value='-1';update();};$('#counterexample').onclick=()=>{pause();state.q=[0,75,75,0];$('#pose').value='-1';update();};
$('#play').onclick=()=>{if(state.playing){pause();return;}state.playing=true;$('#play').textContent='暂停演示';$('#play').setAttribute('aria-pressed','true');const start=performance.now(),path=data.mapping.paths[Math.max(0,+$('#pose').value)];function tick(now){if(!state.playing)return;const f=Math.min(1,(now-start)/6500);state.phase=f;if(state.tab==='joint'){const pos=f*(path.angles_deg.length-1),i=Math.floor(pos),j=Math.min(i+1,path.angles_deg.length-1),u=pos-i;state.q=path.angles_deg[i].map((v,k)=>v*(1-u)+path.angles_deg[j][k]*u);}if(state.tab==='bench'){state.exploded=f>.2&&f<.8;$('#explode').checked=state.exploded;}update();if(f<1)requestAnimationFrame(tick);else pause();}requestAnimationFrame(tick);};
const r=data.results,hold=Math.max(...r.loads.flatMap(c=>['alpha','beta'].map(k=>c.physical_axes[k].required_hold_Nm)));$('#facts').innerHTML=[['单接头 · 目标端点',r.target_count+' 个','保留全部原有目标'],['两叉架 · 连续间隙','≥ '+r.yoke.required_mm+' mm','仅名义几何，不是制造公差'],['弯折轴 · 保持力需求',hold.toFixed(2)+' N·m','载荷计算，尚非实测能力'],['胸肩试排 · 所检模块',(r.clav_count-r.clav_failures)+' / '+r.clav_count,'仍有 '+r.clav_failures+' 个失败端点']].map(x=>'<div class="fact">'+x[0]+'<strong>'+x[1]+'</strong>'+x[2]+'</div>').join('');
const rows=[['两叉架的连续间隙',r.yoke_cells+' 个区间单元；≥0.6 mm','α ±28°、β ±98°。仅该零件对，不包括公差、受力变形及完整接头。'],['完整接头目标端点',r.target_count+' 个，失败 '+r.target_failures+' 个','包含名义金属轴、弹簧、摩擦片、外壳和紧固件。完整插值路径仍未作连续验收。'],['双侧胸肩试排',(r.clav_count-r.clav_failures)+' 个未发现所检穿插；'+r.clav_failures+' 个失败','双侧前收20°失败。连接承力架、胸颈、线束、传感板仍缺；不能称整臂通过。'],['质量与保持力','单接头建模质量约 '+r.loads[0].new_TUT_modeled_mass_g.toFixed(2)+' g','不是完整关节或整机重量。新增器件与载荷始终计入，不以1.2 kg作为硬门槛。'],['国产滑环尺寸','目录包络与保护套可放入','不是采购定型：固定、引线、转矩和通信可靠性待验证。'],['材料与弹簧试验','没有实测数据','提供独立小样、步骤和空白表。目录力和示例挂重均不冒充测量。']];$('#result-table').innerHTML='<table><thead><tr><th>范围</th><th>当前结果</th><th>如何理解</th></tr></thead><tbody>'+rows.map(x=>'<tr>'+x.map(v=>'<td>'+v+'</td>').join('')+'</tr>').join('')+'</tbody></table>';
addEventListener('resize',draw);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',pause);update();window.O10_READY=true;window.O10_STATE=state;window.O10_TEST={tab,update,draw};
})();




