const $ = s => document.querySelector(s);
const labels=['零件','支撑主体','接触层','过渡层','裙边'];
const colors=[[.47,.61,.60,.42],[.06,.56,.35,1],[.92,.54,.09,1],[.22,.58,.76,1],[.60,.38,.76,1]];
const state={report:null,plate:null,buffers:[],yaw:-.65,elevation:.86,zoom:1,pan:[0,0],limit:0,single:false,visible:[true,true,true,true,true],loading:0,ready:false};
const canvas=$('#view');
const gl=canvas.getContext('webgl',{antialias:true,alpha:false});
let program,grid,uniforms,positionLocation;
function shader(kind,source){const s=gl.createShader(kind);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;}
if(gl){
 program=gl.createProgram();
 gl.attachShader(program,shader(gl.VERTEX_SHADER,`attribute vec4 aPosition;uniform vec3 uCenter;uniform vec2 uAngles;uniform vec2 uScale;uniform vec2 uPan;uniform float uLayer;uniform float uSingle;uniform float uGrid;void main(){vec3 p=aPosition.xyz-uCenter;float c=cos(uAngles.x),s=sin(uAngles.x);float x=c*p.x-s*p.y,y=s*p.x+c*p.y;float sy=-sin(uAngles.y)*y+cos(uAngles.y)*p.z;float depth=cos(uAngles.y)*y+sin(uAngles.y)*p.z;bool hidden=uGrid<.5&&(aPosition.w>uLayer+.1||(uSingle>.5&&aPosition.w<uLayer-.1));gl_Position=hidden?vec4(2.,2.,2.,1.):vec4(x*uScale.x+uPan.x,sy*uScale.y+uPan.y,-depth/1000.,1.);}`));
 gl.attachShader(program,shader(gl.FRAGMENT_SHADER,`precision mediump float;uniform vec4 uColor;void main(){gl_FragColor=uColor;}`));
 gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));
 positionLocation=gl.getAttribLocation(program,'aPosition');uniforms={};for(const n of ['uCenter','uAngles','uScale','uPan','uLayer','uSingle','uGrid','uColor'])uniforms[n]=gl.getUniformLocation(program,n);
 const a=[];for(let v=0;v<=180;v+=10)a.push(v,0,0,-1,v,180,0,-1,0,v,0,-1,180,v,0,-1);grid={buffer:gl.createBuffer(),count:a.length/4};gl.bindBuffer(gl.ARRAY_BUFFER,grid.buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(a),gl.STATIC_DRAW);
}
function sizeCanvas(){const r=canvas.getBoundingClientRect();const d=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(r.width*d)||canvas.height!==Math.round(r.height*d)){canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);}draw();}
function draw(){if(!gl||!canvas.width)return;gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(.967,.978,.961,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(program);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);gl.enableVertexAttribArray(positionLocation);const z=state.report?.bounds_mm?.max[2]||60;gl.uniform3f(uniforms.uCenter,90,90,z*.42);gl.uniform2f(uniforms.uAngles,state.yaw,state.elevation);gl.uniform2f(uniforms.uScale,2*state.zoom/(225*canvas.width/canvas.height),2*state.zoom/225);gl.uniform2f(uniforms.uPan,...state.pan);gl.uniform1f(uniforms.uLayer,state.limit);gl.uniform1f(uniforms.uSingle,state.single?1:0);
 function batch(b,color,isGrid){gl.bindBuffer(gl.ARRAY_BUFFER,b.buffer);gl.vertexAttribPointer(positionLocation,4,gl.FLOAT,false,16,0);gl.uniform4fv(uniforms.uColor,color);gl.uniform1f(uniforms.uGrid,isGrid?1:0);gl.drawArrays(gl.LINES,0,b.count);}
 gl.depthMask(false);batch(grid,[.74,.80,.73,.7],true);for(const i of [0,1,3,2,4])if(state.visible[i]&&state.buffers[i]){gl.depthMask(i!==0);batch(state.buffers[i],colors[i],false);}gl.depthMask(true);
}
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function metric(value,label){const n=el('div',undefined,'metric');n.append(el('b',value),el('span',label));return n;}
function fmt(x,n=1){return Number(x).toLocaleString('zh-CN',{maximumFractionDigits:n,minimumFractionDigits:n});}
function renderReport(p,report,reportUrl){$('#plateTitle').textContent=`${p.id} · ${p.title||p.id}`;$('#plateNote').textContent=p.note||'对应盘的实际切片路径；包括三类支撑和外侧裙边。';$('#download').href=p.file||p.project||'#';$('#download').download='';$('#dataLink').href=reportUrl;$('#dataLink').download='';const max=report.bounds_mm?.max||[0,0,0];const grams=report.classes.reduce((a,c)=>a+(c.estimated_mass_g||0),0);$('#metrics').replaceChildren(metric(String(report.layers.length),'切片层（含支撑层）'),metric(fmt(max[2])+' mm','最高挤出路径'),metric(fmt(grams)+' g','打印层估算耗材'),metric(report.out_of_bed_segment_count===0?'通过':'需检查','路径中心线在床面内'));
 $('#stats').replaceChildren(...report.classes.map((c,i)=>{const tr=el('tr');tr.append(el('td',labels[i]),el('td',fmt(c.filament_mm/1000,2)+' m'),el('td',c.estimated_mass_g===undefined?'—':fmt(c.estimated_mass_g,2)+' g'),el('td',String(c.layers)));return tr;}));const warnings=[...(report.warnings||[])];if(report.out_of_bed_segment_count)warnings.push(`有 ${report.out_of_bed_segment_count} 个线段超出 A1 mini 打印范围，需要在工程中重新检查。`);$('#warning').replaceChildren(...warnings.map(x=>el('p',x,'alert')));$('#layer').max=String(Math.max(0,report.layers.length-1));$('#layer').value=$('#layer').max;$('#layer').disabled=false;state.limit=report.layers.length-1;updateLayer();
}
function updateLayer(){if(!state.report)return;const l=state.report.layers[state.limit];$('#layerLabel').textContent=`${state.limit+1} / ${state.report.layers.length} · Z ${fmt(l?.z_mm??0,3)} mm`;draw();}
async function loadPlate(p){const ticket=++state.loading;state.ready=false;state.plate=p;$('#status').textContent='读取实际切片统计…';try{const reportUrl=new URL(p.preview,location.href);const res=await fetch(reportUrl);if(!res.ok)throw Error(`路径数据 ${res.status}`);const report=await res.json();if(ticket!==state.loading)return;state.report=report;renderReport(p,report,reportUrl.href);if(!gl){$('#status').textContent='当前浏览器不支持 WebGL，仍可查看材料统计并下载工程。';return;}$('#status').textContent=`载入 ${fmt(report.binary.bytes/1024/1024,1)} MB 实际路径…`;const binRes=await fetch(new URL(report.binary.file,reportUrl));if(!binRes.ok)throw Error(`路径二进制 ${binRes.status}`);const binary=await binRes.arrayBuffer();if(ticket!==state.loading)return;if(binary.byteLength!==report.segment_count*16)throw Error('路径长度与核查数据不一致');const packed=new Uint16Array(binary);const arrays=report.classes.map(c=>new Float32Array(c.segments*8));const offsets=[0,0,0,0,0],origin=report.binary.origin_mm,q=report.binary.quantum_mm;for(let i=0;i<packed.length;i+=8){const layer=packed[i+6],role=packed[i+7];if(role>4||layer>=report.layers.length)throw Error('路径记录类型或层号无效');const a=arrays[role];let k=offsets[role];a[k++]=origin[0]+packed[i]*q;a[k++]=origin[1]+packed[i+1]*q;a[k++]=origin[2]+packed[i+2]*q;a[k++]=layer;a[k++]=origin[0]+packed[i+3]*q;a[k++]=origin[1]+packed[i+4]*q;a[k++]=origin[2]+packed[i+5]*q;a[k++]=layer;offsets[role]=k;}for(const b of state.buffers)if(b)gl.deleteBuffer(b.buffer);state.buffers=arrays.map(a=>{const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,a,gl.STATIC_DRAW);return{buffer,count:a.length/4};});state.ready=true;$('#status').textContent='';draw();}catch(e){$('#status').textContent=`无法载入预览：${e.message}。若直接双击 HTML，请通过随包的本地预览服务打开。`;}}
$('#plate').addEventListener('change',()=>{const p=window.__o22SupportManifest.plates.find(p=>p.id===$('#plate').value);if(p)loadPlate(p);});$('#layer').addEventListener('input',()=>{state.limit=Number($('#layer').value);updateLayer();});$('#single').addEventListener('change',()=>{state.single=$('#single').checked;draw();});for(const cb of document.querySelectorAll('[data-role]'))cb.addEventListener('change',()=>{state.visible[Number(cb.dataset.role)]=cb.checked;draw();});$('#onlySupport').addEventListener('click',()=>{const model=document.querySelector('[data-role="0"]');model.checked=!model.checked;state.visible[0]=model.checked;$('#onlySupport').textContent=model.checked?'只看支撑':'显示零件';draw();});$('#top').onclick=()=>{state.yaw=0;state.elevation=Math.PI/2;draw();};$('#front').onclick=()=>{state.yaw=0;state.elevation=0;draw();};$('#iso').onclick=()=>{state.yaw=-.65;state.elevation=.86;draw();};$('#reset').onclick=()=>{state.zoom=1;state.pan=[0,0];state.yaw=-.65;state.elevation=.86;draw();};let drag=null;canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY};});canvas.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(e.shiftKey||e.buttons===2){state.pan[0]+=2*dx/canvas.clientWidth;state.pan[1]-=2*dy/canvas.clientHeight;}else{state.yaw+=dx*.008;state.elevation=Math.max(-1.55,Math.min(1.57,state.elevation+dy*.007));}drag={x:e.clientX,y:e.clientY};draw();});canvas.addEventListener('pointerup',()=>drag=null);canvas.addEventListener('pointercancel',()=>drag=null);canvas.addEventListener('wheel',e=>{e.preventDefault();state.zoom=Math.max(.45,Math.min(15,state.zoom*Math.exp(-e.deltaY*.001)));draw();},{passive:false});canvas.addEventListener('contextmenu',e=>e.preventDefault());new ResizeObserver(sizeCanvas).observe(canvas);
window.__o22SupportViewer={get state(){return{ready:state.ready,plate:state.plate?.id,layer:state.limit,report:state.report,vertices:state.buffers.map(b=>b.count),glError:gl?.getError()};}};
try{const r=await fetch('manifest.json');if(!r.ok)throw Error(`索引 ${r.status}`);const manifest=await r.json();window.__o22SupportManifest=manifest;if(!manifest.plates?.length)throw Error('没有可预览的打印盘');$('#plate').replaceChildren(...manifest.plates.map(p=>{const o=el('option',`${p.id} · ${p.title||p.id}`);o.value=p.id;return o;}));if(manifest.notes)$('#manifestNotes').replaceChildren(...manifest.notes.map(n=>el('p',n)));const wanted=new URLSearchParams(location.search).get('plate');const first=manifest.plates.find(p=>p.id===wanted)||manifest.plates[0];$('#plate').value=first.id;await loadPlate(first);}catch(e){$('#status').textContent=`预览索引暂不可用：${e.message}`;}
