const { chromium }=require('C:/Users/Ding/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),path=require('path'),assert=require('assert');
const out=path.resolve(__dirname,'../verification');
(async()=>{
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});const errors=[],checks=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.goto('http://127.0.0.1:8769/tutorials/design-lab/index.html',{waitUntil:'networkidle'});await page.waitForFunction(()=>window.O10_READY===true).catch(async e=>{console.error(JSON.stringify({errors,globals:await page.evaluate(()=>({models:!!window.O10_MODELS,data:!!window.O10_DATA}))}));throw e;});await page.waitForTimeout(150);
 assert.equal(await page.locator('#facts .fact').count(),4);checks.push('four scoped evidence cards loaded');
 let pixels=await page.evaluate(()=>{const c=document.querySelector('canvas'),gl=c.getContext('webgl'),p=new Uint8Array(c.width*c.height*4);gl.readPixels(0,0,c.width,c.height,gl.RGBA,gl.UNSIGNED_BYTE,p);let n=0;for(let i=0;i<p.length;i+=4)if(Math.abs(p[i]-228)+Math.abs(p[i+1]-233)+Math.abs(p[i+2]-221)>30)n++;return n;});assert(pixels>3000);checks.push('nonblank WebGL model rendered');
 await page.screenshot({path:path.join(out,'joint-desktop.png'),fullPage:true});
 await page.locator('#counterexample').click();assert(await page.locator('#joint-status').evaluate(e=>e.classList.contains('bad')));assert.equal(await page.evaluate(()=>window.O10_STATE.q[1]),75);assert(await page.locator('#sliders').isHidden());checks.push('preserved 75/75 failure is explicit, outside-limit sliders hidden');
 await page.locator('#straight').click();assert.equal(await page.evaluate(()=>window.O10_STATE.q[2]),0);assert(await page.locator('#sliders').isVisible());
 await page.locator('#model').focus();const yaw=await page.evaluate(()=>window.O10_STATE.yaw);await page.keyboard.press('ArrowRight');assert.notEqual(await page.evaluate(()=>window.O10_STATE.yaw),yaw);checks.push('keyboard model controls work');
 await page.locator('[data-tab="shoulder"]').click();await page.locator('#body-pose').selectOption('1');assert.match(await page.locator('#body-status').textContent(),/穿插/);await page.locator('#character').selectOption('quinn');assert.match(await page.locator('#body-status').textContent(),/4 对/);await page.screenshot({path:path.join(out,'shoulder-failure.png'),fullPage:true});checks.push('both-character bilateral collision endpoints retained');
 await page.locator('[data-tab="wire"]').click();await page.screenshot({path:path.join(out,'wire-candidate.png'),fullPage:true});assert.match(await page.locator('[data-panel="wire"]').textContent(),/尚未购买/);checks.push('slip ring is a conditional candidate with no hardware claim');
 await page.locator('[data-tab="bench"]').click();assert.match(await page.locator('#torque').textContent(),/0\.196 N/);await page.locator('#mass').evaluate(e=>{e.value='500';e.dispatchEvent(new Event('input',{bubbles:true}));});assert.match(await page.locator('#torque').textContent(),/0\.490 N/);await page.locator('#mass').evaluate(e=>{e.value='200';e.dispatchEvent(new Event('input',{bubbles:true}));});await page.screenshot({path:path.join(out,'bench-assembled.png'),fullPage:true});await page.locator('#explode').check();await page.screenshot({path:path.join(out,'bench-exploded.png'),fullPage:true});checks.push('hanging-mass arithmetic agrees with 0.1 m physical lever arm');
 await page.locator('#play').click();await page.waitForTimeout(350);assert(await page.evaluate(()=>window.O10_STATE.playing));await page.locator('[data-tab="evidence"]').click();assert(!(await page.evaluate(()=>window.O10_STATE.playing)));assert.equal(await page.locator('#result-table tbody tr').count(),6);checks.push('animation stops on navigation and evidence boundaries remain distinct');
 const links=await page.locator('a[href]').evaluateAll(xs=>xs.map(x=>x.getAttribute('href')).filter(x=>!x.startsWith('http')));for(const href of links){if(href.endsWith('evidence_manifest.json'))continue;const response=await page.request.get(new URL(href,page.url()).href);assert(response.ok(),href);}checks.push('local guide, history and measurement links resolve');
 await page.setViewportSize({width:390,height:844});await page.locator('[data-tab="bench"]').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(out,'bench-mobile.png'),fullPage:true});await page.locator('[data-tab="evidence"]').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));checks.push('mobile layouts do not overflow');
 assert.deepEqual(errors,[]);checks.push('no page or console errors');fs.writeFileSync(path.join(out,'checks.json'),JSON.stringify({status:'PASS',checks,non_background_pixels:pixels,errors,hardware_tested:false},null,2)+'\n');console.log(JSON.stringify({status:'PASS',checks:checks.length,pixels}));await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});


