'use strict';
(()=>{const $=s=>document.querySelector(s),S=window.O13_SCENES,M=window.O13_MODELS,state={character:'quinn',pose:0,focus:false,core:false,alpha:0,beta:0,yaw:-1.17,pitch:-1.34,zoom:1,geometry:true},cache={};let timer=null;
const I=()=>[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],mul=(a,b)=>Array.from({length:16},(_,k)=>[0,1,2,3].reduce((s,i)=>s+a[Math.floor(k/4)*4+i]*b[i*4+k%4],0)),col=m=>new Float32Array(Array.from({length:16},(_,i)=>m[i%4*4+Math.floor(i/4)]));
function R(axis,a){const m=I(),c=Math.cos(a),s=Math.sin(a);if(axis==='x'){m[5]=c;m[6]=-s;m[9]=s;m[10]=c;}else if(axis==='y'){m[0]=c;m[2]=s;m[8]=-s;m[10]=c;}else{m[0]=c;m[1]=-s;m[4]=s;m[5]=c;}return m;}
function T(p){const m=I();m[3]=p[0];m[7]=p[1];m[11]=p[2];return m;}
const canvas=$('#model'),gl=canvas.getContext('webgl',{antialias:true,preserveDrawingBuffer:true});let L;
if(gl){const shader=(type,src)=>{const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;},p=gl.createProgram();gl.attachShader(p,shader(gl.VERTEX_SHADER,'attribute vec3 p;attribute vec3 n;uniform mat4 M;uniform vec2 scale;varying vec3 normal;void main(){vec4 v=M*vec4(p,1.);normal=(M*vec4(n,0.)).xyz;gl_Position=vec4(v.x*scale.x,v.y*scale.y,-v.z/1800.,1.);gl_PointSize=9.;}'));gl.attachShader(p,shader(gl.FRAGMENT_SHADER,'precision mediump float;varying vec3 normal;uniform vec3 color;void main(){float l=.5+.5*max(0.,dot(normalize(normal),normalize(vec3(-.4,.7,1.))));gl_FragColor=vec4(color*l,1.);}'));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));gl.useProgram(p);L={p:gl.getAttribLocation(p,'p'),n:gl.getAttribLocation(p,'n'),M:gl.getUniformLocation(p,'M'),scale:gl.getUniformLocation(p,'scale'),color:gl.getUniformLocation(p,'color')};gl.enable(gl.DEPTH_TEST);}else $('#gl-error').hidden=false;
function buffer(a){const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(a),gl.STATIC_DRAW);return {b,count:a.length/6};}
function mesh(key){if(cache[key])return cache[key];const o=M[key],a=[];for(const f of o.f){const [p,q,r]=f.map(i=>o.v[i]),u=q.map((x,i)=>x-p[i]),v=r.map((x,i)=>x-p[i]);let n=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]],d=Math.hypot(...n)||1;n=n.map(x=>x/d);for(const p0 of [p,q,r])a.push(...p0,...n);}return cache[key]=buffer(a);}
const scenes=()=>S.filter(s=>s.character===state.character);
function coreScene(){const A=R('x',state.alpha*Math.PI/180),B=mul(A,R('y',state.beta*Math.PI/180));return {objects:O13_CORE.map(o=>({...o,frame:o.group==='input'?I():o.group==='ring'?A:B})),bones:[],support_points:[],whole_arm_findings:[]};}
function draw(){if(!gl)return;const w=canvas.clientWidth,h=canvas.clientHeight,dpr=Math.min(devicePixelRatio||1,2);canvas.width=w*dpr;canvas.height=h*dpr;gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(.905,.925,.875,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const scene=state.core?coreScene():scenes()[state.pose],center=state.core?[0,0,0]:state.focus?[0,0,380]:[0,0,245],radius=state.core?55:state.focus?115:280,scale=Math.min(w,h)*.46/radius*state.zoom;const view=mul(mul(R('x',state.pitch),R('z',state.yaw)),T(center.map(x=>-x)));gl.uniform2f(L.scale,2*scale/w,2*scale/h);
function render(b,m,c,mode=gl.TRIANGLES){gl.bindBuffer(gl.ARRAY_BUFFER,b.b);gl.enableVertexAttribArray(L.p);gl.vertexAttribPointer(L.p,3,gl.FLOAT,false,24,0);gl.enableVertexAttribArray(L.n);gl.vertexAttribPointer(L.n,3,gl.FLOAT,false,24,12);gl.uniformMatrix4fv(L.M,false,col(m));gl.uniform3fv(L.color,c);gl.drawArrays(mode,0,b.count);}
const findings=scene.whole_arm_findings||[],bad=new Set(findings.filter(f=>f.classification==='STRUCTURAL_ADJACENT_OR_SAME_JOINT').flatMap(f=>f.pair)),contact=new Set(findings.filter(f=>f.classification==='POSE_AVOIDABLE_NONADJACENT_CONTACT').flatMap(f=>f.pair));
if(state.geometry)for(const o of scene.objects)render(mesh(o.key),mul(view,o.frame.flat()),bad.has(o.label)?[.80,.28,.20]:contact.has(o.label)?[.85,.54,.15]:o.role==='reserved_geometry'?[.76,.60,.26]:o.label.includes('TUT')?[.31,.48,.40]:[.49,.53,.51]);
const lines=[];for(const b of scene.bones)lines.push(...b.a,0,0,1,...b.b,0,0,1);const lb=buffer(lines);render(lb,view,[.40,.46,.43],gl.LINES);gl.deleteBuffer(lb.b);
const pb=buffer(scene.support_points.flatMap(p=>[...p,0,0,1]));render(pb,view,[.76,.49,.16],gl.POINTS);gl.deleteBuffer(pb.b);
$('#coverage').textContent=state.core?'双轴核心试装候选 · 实物效果待测':scene.reference_only_pose?'全身姿态参考 · 下肢仍为骨架':(bad.size?'红色：同一或相邻关节干涉，需改设计':contact.size?'橙色：非相邻部位接触，需调整姿势':'该端点未检出所检零件穿插；非整机验收');
}
const names={neutral:'中立站姿',arms_forward:'双臂前举',arms_overhead:'双臂上举',arms_side:'双臂侧举',hands_on_hips:'双手叉腰',forehead:'手到额前',sitting:'坐姿参考',crouch:'下蹲参考',head_tilt:'头部倾斜参考',hip_abduction:'髋外展参考',trunk_bend_twist:'躯干弯曲扭转参考',legs_crossed:'交叉腿参考',arms_crossed:'对称抱臂',palms_turn:'翻转手掌',arms_crossed_asymmetric_candidate:'一高一低抱臂'};
function label(s){return names[s.pose]||s.pose.replace('clavicle_l.protract_','双肩前收 ').replace('clavicle_l.elevate_','双肩上提 ').replace('upperarm_l.abduct_','上臂外展 ').replace('upperarm_l.flex_','上臂屈伸 ').replace('upperarm_l.twist_','上臂转动 ').replace('elbow_l.flex_','屈肘 ').replace('forearm_l.twist_','前臂转动 ').replace('hand_l.flex_','手腕屈伸 ').replace('hand_l.deviate_','手腕侧偏 ').replace('back_reach_','向后伸手 ').replace('waist_pitch_','腰部前后弯 ').replace('waist_roll_','腰部侧弯 ').replace('chest_pitch_','胸部前后弯 ').replace('chest_roll_','胸部侧弯 ').replace('_arm_side','° / 双臂侧举');}
function fill(){state.pose=0;$('#pose').replaceChildren(...scenes().map((s,i)=>new Option(label(s),i)));draw();}
function pause(){if(timer)clearInterval(timer);timer=null;$('#cycle').textContent='轮播检查姿态';}
$('#character').onchange=()=>{pause();if(state.core)focus(false);state.character=$('#character').value;fill();};$('#pose').onchange=()=>{pause();if(state.core)focus(false);state.pose=+$('#pose').value;draw();};
$('#geometry').onchange=()=>{state.geometry=$('#geometry').checked;draw();};
function focus(v){state.core=false;$('#core-controls').hidden=true;$('#core').classList.remove('active');state.focus=v;state.zoom=1;$('#full').classList.toggle('active',!v);$('#shoulders').classList.toggle('active',v);$('#scene-title').textContent=v?'肩部布局':'全身布局';draw();}
$('#full').onclick=()=>focus(false);$('#shoulders').onclick=()=>focus(true);$('#reset').onclick=()=>{state.yaw=state.core?-.8:-1.17;state.pitch=state.core?-.7:-1.34;state.zoom=1;draw();};
$('#core').onclick=()=>{pause();state.core=true;state.focus=false;state.zoom=1;state.yaw=-.8;state.pitch=-.7;$('#core-controls').hidden=false;$('#core').classList.add('active');$('#full').classList.remove('active');$('#shoulders').classList.remove('active');$('#scene-title').textContent='双轴核心';draw();};for(const key of ['alpha','beta'])$('#'+key).oninput=e=>{state[key]=Number(e.target.value);$('#'+key+'-text').textContent=state[key]+'°';draw();};
$('#cycle').onclick=()=>{if(state.core)focus(false);if(timer){pause();return;}$('#cycle').textContent='暂停轮播';timer=setInterval(()=>{state.pose=(state.pose+1)%scenes().length;$('#pose').value=state.pose;draw();},1800);};
let drag=null;canvas.onpointerdown=e=>{drag=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(drag){state.yaw+=(e.clientX-drag[0])*.006;state.pitch+=(e.clientY-drag[1])*.006;drag=[e.clientX,e.clientY];draw();}};canvas.onpointerup=canvas.onpointercancel=()=>drag=null;canvas.onwheel=e=>{e.preventDefault();state.zoom=Math.max(.5,Math.min(4,state.zoom*Math.exp(-e.deltaY*.001)));draw();};canvas.onkeydown=e=>{if(!e.key.startsWith('Arrow'))return;e.preventDefault();state.yaw+=e.key==='ArrowLeft'?-.1:e.key==='ArrowRight'?.1:0;state.pitch+=e.key==='ArrowUp'?-.1:e.key==='ArrowDown'?.1:0;draw();};
const r=window.O13_RESULTS;$('#facts').innerHTML=[['原小样实物反馈','装配通过','继续使用；保持力数值待补测'],['肩部额外外移','0 mm','已恢复 UE 缩放参考肩宽'],['同一 / 相邻关节',r.adjacentFailures+' / '+r.cases+' 端点干涉','仅当前实际手臂模型与连接架'],['非相邻部位',r.nonadjacentContacts+' / '+r.cases+' 端点接触','保留橙色提示，通过调整姿势避开']].map(x=>'<div class=fact>'+x[0]+'<strong>'+x[1]+'</strong><span>'+x[2]+'</span></div>').join('');
window.O13_TEST={state,draw,focus,scenes};window.O13_READY=true;addEventListener('resize',draw);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});fill();
})();