'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert'),{pathToFileURL}=require('url');
const {chromium}=require('C:/Users/Ding/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),out=path.join(root,'verification');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--enable-unsafe-swiftshader']});const errors=[],checks=[];try{
 const page=await browser.newPage({viewport:{width:1440,height:1100}});page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.join(root,'index.html')).href);await page.waitForFunction(()=>window.TUT_GUIDE_READY);assert.strictEqual(await page.locator('#webgl-error').isVisible(),false);
 const image=()=>page.locator('#model').evaluate(c=>c.toDataURL());let before=await image();await page.locator('#model').focus();await page.keyboard.press('ArrowLeft');assert.notStrictEqual(await image(),before);await page.click('#reset');checks.push('WebGL renders; keyboard changes camera');
 await page.selectOption('#preset','single');assert((await page.innerText('#pose-result')).includes('0.6 mm'));before=await image();await page.click('[data-version=original]');assert((await page.innerText('#pose-result')).includes('穿透'));assert.notStrictEqual(await image(),before);await page.click('[data-version=extended]');await page.selectOption('#preset','mixed');assert((await page.innerText('#pose-result')).includes('均已发现'));checks.push('Compared actual original/new mesh and preserved failure warning');
 await page.locator('#alpha').evaluate(e=>{e.value='22';e.dispatchEvent(new Event('input'));});await page.click('[data-version=original]');assert((await page.innerText('#pose-result')).includes('不自动判定'));checks.push('Unlisted angles never inherit a pass badge');await page.click('[data-version=extended]');await page.selectOption('#preset','neutral');
 for(const tab of ['design','assembly','fit','record']){await page.click('[data-tab='+tab+']');await page.locator('#'+tab).waitFor({state:'visible'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(out,'desktop-'+tab+'.png'),fullPage:true});}
 await page.click('[data-tab=assembly]');await page.locator('#assembly').waitFor({state:'visible'});const positions=new Set();for(let i=0;i<6;i++){await page.click('[data-step="'+i+'"]');await page.locator('#progress').evaluate(e=>{e.value='70';e.dispatchEvent(new Event('input'));});positions.add(await image());assert.strictEqual(await page.innerText('#percent'),'70%');}assert.strictEqual(positions.size,6);await page.click('[data-step="1"]');before=await image();await page.click('#play');await page.waitForFunction(()=>window.TUT_GUIDE_STATE.progress>5);assert.notStrictEqual(await image(),before);await page.click('#play');const prog=await page.inputValue('#progress');await page.waitForTimeout(100);assert.strictEqual(await page.inputValue('#progress'),prog);checks.push('Six assembly stages; play, pause and scrub move distinct geometry');
 await page.click('[data-tab=fit]');await page.locator('#fit').waitFor({state:'visible'});const parts=await page.locator('#part option').evaluateAll(e=>e.map(o=>o.value)),drawings=new Set();for(const v of parts){await page.selectOption('#part',v);drawings.add(await image());assert((await page.innerText('#part-text')).length>30);}assert.strictEqual(drawings.size,6);checks.push('All six gauge / fastener models visible with instructions');
 for(const tab of ['design','assembly','fit','record']){await page.setViewportSize({width:375,height:850});await page.click('[data-tab='+tab+']');await page.locator('#'+tab).waitFor({state:'visible'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'overflow '+tab);await page.screenshot({path:path.join(out,'mobile-'+tab+'.png'),fullPage:true});}checks.push('Four chapters at desktop and 375 px; no horizontal overflow');
 const links=await page.locator('a[href]').evaluateAll(as=>as.map(a=>a.getAttribute('href')).filter(x=>!x.startsWith('#')&&!/^https?:/.test(x)));for(const href of links)assert(fs.existsSync(path.resolve(root,href)),'Missing '+href);checks.push('All local download, report and provenance links resolve');
 assert.deepStrictEqual(errors,[]);fs.writeFileSync(path.join(out,'checks.json'),JSON.stringify({status:'PASS',checks,viewports:[1440,375],pageErrors:errors,mode:'offline file URL / headless Chrome',physical_tested:false},null,2));console.log('PASS',checks.length,'groups');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
