'use strict';
const $=s=>document.querySelector(s);
const dialog=$('#viewer');
let state={step:'S01',part:'',isolate:false,metal:true,electronics:true,explode:0,yaw:-1.08,pitch:-1.28,zoom:1};
let guide,scene,gl,canvas,program,L,buffer,readyPromise;
const I=()=>[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];
const mul=(a,b)=>Array.from({length:16},(_,k)=>[0,1,2,3].reduce((s,j)=>s+a[Math.floor(k/4)*4+j]*b[j*4+k%4],0));
const col=a=>new Float32Array(Array.from({length:16},(_,k)=>a[k%4*4+Math.floor(k/4)]));
function R(axis,a){const m=I(),c=Math.cos(a),s=Math.sin(a);if(axis===0){m[5]=c;m[6]=-s;m[9]=s;m[10]=c}else{m[0]=c;m[1]=-s;m[4]=s;m[5]=c}return m}
function T(v){const m=I();m[3]=v[0];m[7]=v[1];m[11]=v[2];return m}
async function json(url){const r=await fetch(url);if(!r.ok)throw Error(`${url}：${r.status}`);return r.json()}
function shader(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}
function selectedStep(){return guide.steps.find(s=>s.step===state.step)}
function objects(){const s=selectedStep(),set=new Set(s.objects);return scene.objects.filter(o=>set.has(o.label)&&(!state.isolate||!state.part||o.label===state.part)&&(o.role!=='metal'||state.metal||o.label===state.part)&&(!['equipment','sensor','tail'].includes(o.role)||state.electronics||o.label===state.part)&&(o.label!=='o22/controller_lid'||state.part===o.label))}
function draw(){if(!gl||!dialog.open)return;const obs=objects();if(!obs.length)return;const w=canvas.clientWidth,h=canvas.clientHeight,dpr=Math.min(devicePixelRatio||1,2);canvas.width=w*dpr;canvas.height=h*dpr;gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(.914,.933,.894,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);
 const lo=[Infinity,Infinity,Infinity],hi=[-Infinity,-Infinity,-Infinity];for(const o of obs)for(let i=0;i<3;i++){const ex=(o.explode?.[i]||0)*state.explode;lo[i]=Math.min(lo[i],o.bounds[0][i]+ex);hi[i]=Math.max(hi[i],o.bounds[1][i]+ex)}
 const center=lo.map((v,i)=>(v+hi[i])/2),radius=Math.max(8,Math.hypot(...lo.map((v,i)=>hi[i]-v))/2);const view=mul(mul(R(0,state.pitch),R(2,state.yaw)),T(center.map(x=>-x)));const plo=[Infinity,Infinity],phi=[-Infinity,-Infinity];for(const o of obs)for(const x of [o.bounds[0][0],o.bounds[1][0]])for(const y of [o.bounds[0][1],o.bounds[1][1]])for(const z of [o.bounds[0][2],o.bounds[1][2]]){const p=[x,y,z].map((v,i)=>v+(o.explode?.[i]||0)*state.explode);for(let i=0;i<2;i++){const v=view[i*4]*p[0]+view[i*4+1]*p[1]+view[i*4+2]*p[2]+view[i*4+3];plo[i]=Math.min(plo[i],v);phi[i]=Math.max(phi[i],v)}}view[3]-=(plo[0]+phi[0])/2;view[7]-=(plo[1]+phi[1])/2;const scale=Math.min(w*.88/Math.max(1,phi[0]-plo[0]),h*.88/Math.max(1,phi[1]-plo[1]))*state.zoom;
 gl.uniform2f(L.sc,2*scale/w,2*scale/h);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.enableVertexAttribArray(L.p);gl.vertexAttribPointer(L.p,3,gl.FLOAT,false,24,0);gl.enableVertexAttribArray(L.n);gl.vertexAttribPointer(L.n,3,gl.FLOAT,false,24,12);
 const s=selectedStep();for(const o of obs){const mesh=scene.meshes[o.mesh],m=o.matrix.slice();for(let i=0;i<3;i++)m[i*4+3]+=(o.explode?.[i]||0)*state.explode;let c=o.color||(o.role==='metal'?[.63,.67,.69]:o.role==='sensor'?[.26,.48,.38]:o.role==='equipment'?[.30,.42,.34]:[.52,.69,.57]);if(o.label==='frame/'+s.parent)c=[.33,.57,.77];if(o.label==='frame/'+s.child)c=[.9,.59,.33];if(o.label===state.part)c=[.83,.32,.60];gl.uniformMatrix4fv(L.M,false,col(mul(view,m)));gl.uniform3fv(L.color,c);gl.drawArrays(gl.TRIANGLES,mesh.first,mesh.count)}
 window.O22_ASSEMBLY_LAST_DRAW={step:state.step,objects:obs.length,part:state.part,isolate:state.isolate};
}
function updateStep(){const s=selectedStep();state.yaw=s.step==='S26'?Math.PI/2:-1.08;state.pitch=s.step==='S26'?-Math.PI/2:-1.28;$('#viewer-title').textContent=s.step+' · '+s.title;$('#view-step-select').value=s.step;state.part='';state.isolate=false;state.explode=0;state.zoom=1;$('#isolate').checked=false;$('#view-explode').value=0;const set=new Set(s.objects);const obs=scene.objects.filter(o=>set.has(o.label));obs.sort((a,b)=>Number(!a.print_id)-Number(!b.print_id)||a.label.localeCompare(b.label));$('#view-part-select').replaceChildren(new Option('显示全部，选择一件高亮',''),...obs.map(o=>new Option(o.address?`盘 ${o.address} · ${o.print_id} ${o.name_zh}`:`${o.label} · ${o.sku||o.role}`,o.label)));$('#view-part-info').textContent=s.step==='S26'?'背盖默认隐藏，便于看清中央板；从零件列表选择背盖可显示。':'相同 N003 / N004 必须同时核对盘内序号与所属关节。';draw()}
async function load(){if(location.protocol==='file:')throw Error('离线文字和图可直接阅读；可旋转 CAD 请通过本地预览服务打开。');[guide,scene]=await Promise.all([json('guide-data.json'),json('scene.json')]);const res=await fetch(scene.geometry_url);if(!res.ok)throw Error('几何文件载入失败');const raw=await res.arrayBuffer();canvas=$('#model');gl=canvas.getContext('webgl',{antialias:true,preserveDrawingBuffer:true});if(!gl)throw Error('浏览器不支持 WebGL，仍可使用页面 CAD 图片和清单。');program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,'attribute vec3 p;attribute vec3 n;uniform mat4 M;uniform vec2 sc;varying vec3 normal;void main(){vec4 v=M*vec4(p,1.);normal=(M*vec4(n,0.)).xyz;gl_Position=vec4(v.x*sc.x,v.y*sc.y,-v.z/2500.,1.);}'));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,'precision mediump float;uniform vec3 color;varying vec3 normal;void main(){float l=.48+.52*abs(dot(normalize(normal),normalize(vec3(-.4,.7,1.))));gl_FragColor=vec4(color*l,1.);}'));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);L={p:gl.getAttribLocation(program,'p'),n:gl.getAttribLocation(program,'n'),M:gl.getUniformLocation(program,'M'),sc:gl.getUniformLocation(program,'sc'),color:gl.getUniformLocation(program,'color')};buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(raw),gl.STATIC_DRAW);gl.enable(gl.DEPTH_TEST);
 $('#view-step-select').replaceChildren(...guide.steps.map(s=>new Option(s.step+' · '+s.title,s.step)));$('#view-step-select').onchange=e=>{state.step=e.target.value;updateStep()};$('#view-part-select').onchange=e=>{state.part=e.target.value;const p=guide.parts[state.part];$('#view-part-info').textContent=p?`盘 ${p.address} / ${p.id} / ${state.part}，首次在 ${guide.first_use[state.part]} 领用`:(state.part||'显示本关节');draw()};$('#isolate').onchange=e=>{state.isolate=e.target.checked;state.zoom=1;draw()};$('#show-metal').onchange=e=>{state.metal=e.target.checked;draw()};$('#show-electronics').onchange=e=>{state.electronics=e.target.checked;draw()};$('#view-explode').oninput=e=>{state.explode=Number(e.target.value);draw()};$('#view-front').onclick=()=>{state.yaw=-Math.PI/2;state.pitch=-Math.PI/2;state.zoom=1;draw()};$('#view-side').onclick=()=>{state.yaw=0;state.pitch=-Math.PI/2;state.zoom=1;draw()};$('#view-reset').onclick=()=>{state.yaw=-1.08;state.pitch=-1.28;state.zoom=1;state.explode=0;$('#view-explode').value=0;draw()};let drag=null;canvas.onpointerdown=e=>{drag=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!drag)return;state.yaw+=(e.clientX-drag[0])*.006;state.pitch+=(e.clientY-drag[1])*.006;drag=[e.clientX,e.clientY];draw()};canvas.onpointerup=canvas.onpointercancel=()=>drag=null;canvas.onwheel=e=>{e.preventDefault();state.zoom=Math.max(.25,Math.min(6,state.zoom*Math.exp(-e.deltaY*.001)));draw()};canvas.onkeydown=e=>{if(!e.key.startsWith('Arrow'))return;e.preventDefault();state.yaw+=e.key==='ArrowLeft'?-.1:e.key==='ArrowRight'?.1:0;state.pitch+=e.key==='ArrowUp'?-.1:e.key==='ArrowDown'?.1:0;draw()};$('#viewer-status').textContent='原始 CAD 已载入 · 仅作装配位置与单件识别';addEventListener('resize',draw);window.O22_ASSEMBLY={state,guide,scene,draw};}
async function openStep(id){state.step=id;if(!dialog.open)dialog.showModal();try{if(!readyPromise)readyPromise=load();await readyPromise;updateStep()}catch(e){$('#viewer-status').textContent=e.message;console.error(e)}}
document.querySelectorAll('.view-step').forEach(b=>b.onclick=()=>openStep(b.dataset.step));$('#viewer-close').onclick=()=>dialog.close();
$('#wire-search').oninput=e=>{const q=e.target.value.toLowerCase();let visible=0;document.querySelectorAll('#wire-table tbody tr').forEach(r=>{r.hidden=!r.textContent.toLowerCase().includes(q);if(!r.hidden)visible++});$('#wire-filter-state').textContent=`显示 ${visible} / 46 路`;};
let printDetails=[];addEventListener('beforeprint',()=>{printDetails=[...document.querySelectorAll('details:not([open])')];printDetails.forEach(d=>d.open=true)});addEventListener('afterprint',()=>{printDetails.forEach(d=>d.open=false)});
