'use strict';
(()=>{
const $=s=>document.querySelector(s),models=window.O11_MODELS,groups=window.O11_GROUPS,state={mode:'bench',e:0,yaw:-.25,pitch:-.45,zoom:1,playing:false,selected:''};
const I=()=>[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],mul=(a,b)=>Array.from({length:16},(_,k)=>[0,1,2,3].reduce((s,i)=>s+a[Math.floor(k/4)*4+i]*b[i*4+k%4],0));
function R(axis,a){const m=I(),c=Math.cos(a),s=Math.sin(a);if(axis==='x'){m[5]=c;m[6]=-s;m[9]=s;m[10]=c;}else if(axis==='y'){m[0]=c;m[2]=s;m[8]=-s;m[10]=c;}else{m[0]=c;m[1]=-s;m[4]=s;m[5]=c;}return m;}
function T(x,y,z){const m=I();m[3]=x;m[7]=y;m[11]=z;return m;}
const col=m=>new Float32Array(Array.from({length:16},(_,i)=>m[(i%4)*4+Math.floor(i/4)])),color=h=>[1,3,5].map(i=>parseInt(h.slice(i,i+2),16)/255);
const canvas=$('#model'),gl=canvas.getContext('webgl',{antialias:true,preserveDrawingBuffer:true}),cache={};let loc;
if(gl){const shader=(type,src)=>{const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;};const p=gl.createProgram();gl.attachShader(p,shader(gl.VERTEX_SHADER,'attribute vec3 p;attribute vec3 n;uniform mat4 M;uniform vec2 scale;varying vec3 normal;void main(){vec4 v=M*vec4(p,1.);normal=normalize((M*vec4(n,0.)).xyz);gl_Position=vec4(v.x*scale.x,v.y*scale.y,-v.z/1000.,1.);}'));gl.attachShader(p,shader(gl.FRAGMENT_SHADER,'precision mediump float;varying vec3 normal;uniform vec3 color;void main(){float l=.4+.6*max(0.,dot(normalize(normal),normalize(vec3(-.4,.7,1.))));gl_FragColor=vec4(color*l,1.);}'));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));gl.useProgram(p);loc={p:gl.getAttribLocation(p,'p'),n:gl.getAttribLocation(p,'n'),M:gl.getUniformLocation(p,'M'),scale:gl.getUniformLocation(p,'scale'),color:gl.getUniformLocation(p,'color')};gl.enable(gl.DEPTH_TEST);}else $('#gl-error').hidden=false;
function mesh(key){if(cache[key])return cache[key];const o=models[key],a=[];for(const f of o.f){const [p,q,r]=f.map(i=>o.v[i]),u=q.map((x,i)=>x-p[i]),v=r.map((x,i)=>x-p[i]);let n=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]],l=Math.hypot(...n)||1;n=n.map(x=>x/l);for(const p0 of [p,q,r])a.push(...p0,...n);}const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(a),gl.STATIC_DRAW);return cache[key]={b,count:a.length/6};}
function offset(k){const e=state.e;if(state.mode==='bench'){if(k==='printed_base_minus')return[0,-15*e,0];if(k==='printed_base_plus')return[0,15*e,0];if(k.startsWith('case_'))return[0,k.includes('nut')?-20*e:20*e,0];if(k==='M3_nut'||k==='M3_reaction_washer')return[0,0,-12*e];const dz={inner_M4_wide:10,printed_lever:20,outer_M4_wide:30,spring_1:40,spring_2:48,front_M4_washer:58,shoulder_SBSM_M3_4_8:68};return[0,0,(dz[k]||0)*e];}if(k==='C01')return[0,0,-25*e];if(k==='C02')return[0,0,25*e];if(k==='C14')return[0,0,-10*e];if(k==='C15')return[0,0,10*e];if(k.includes('_-1_')||k.includes('_+1_')){const side=k.includes('_-1_')?-1:1;return k.startsWith('C01')?[side*20*e,0,0]:[0,side*20*e,0];}return[0,0,0];}
function draw(){if(!gl)return;const w=canvas.clientWidth,h=canvas.clientHeight,dpr=Math.min(devicePixelRatio||1,2);canvas.width=w*dpr;canvas.height=h*dpr;gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(.89,.91,.865,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const center=state.mode==='bench'?[40,0,12+state.e*26]:[0,0,2],radius=state.mode==='bench'?78:52+state.e*15,scale=Math.min(w,h)*.46/radius*state.zoom;let view=mul(R('x',state.pitch),R('z',state.yaw));if(state.mode==='bench')view=mul(R('y',.45),view);view=mul(view,T(...center.map(x=>-x)));gl.uniform2f(loc.scale,2*scale/w,2*scale/h);for(const o of groups[state.mode]){const b=mesh(o.key);gl.bindBuffer(gl.ARRAY_BUFFER,b.b);gl.enableVertexAttribArray(loc.p);gl.vertexAttribPointer(loc.p,3,gl.FLOAT,false,24,0);gl.enableVertexAttribArray(loc.n);gl.vertexAttribPointer(loc.n,3,gl.FLOAT,false,24,12);gl.uniformMatrix4fv(loc.M,false,col(mul(view,T(...offset(o.name)))));let c=color(o.name===state.selected?'#e7b858':o.color);if(state.selected&&o.name!==state.selected)c=c.map(x=>x*.65+.28);gl.uniform3fv(loc.color,c);gl.drawArrays(gl.TRIANGLES,0,b.count);}}
function pause(){state.playing=false;$('#animate').textContent='播放拆装示意';$('#animate').setAttribute('aria-pressed','false');}
function reset(){state.yaw=state.mode==='bench'?-.25:.45;state.pitch=state.mode==='bench'?-.45:-1.05;state.zoom=1;draw();}
function tab(mode){pause();state.mode=mode;state.e=0;state.selected='';$('#explode').value=0;for(const n of ['bench','core']){$('#'+n).classList.toggle('active',n===mode);$('#'+n).setAttribute('aria-pressed',String(n===mode));}$('#scene-title').textContent=mode==='bench'?'一套可以单独做的小样':'打印承力环 + 标准轴肩螺钉';$('#scene-detail').textContent=mode==='bench'?'先用它测打印材料的保持力、摆动阻力和长期受压变化。测试不需要购买整个人偶的电子器件。':'两个环半件夹住螺母和大垫圈，叉架绕成品光轴转动。这里展示双轴核心；胸肩布局、外侧转动座和传感器仍有独立验证项目。';$('#part').replaceChildren(new Option('显示全部零件',''),...groups[mode].map(o=>new Option(o.label,o.name)));$('#part-info').textContent='选择零件后，它会以亮色突出显示。';reset();}
$('#bench').onclick=()=>tab('bench');$('#core').onclick=()=>tab('core');$('#reset').onclick=reset;$('#part').onchange=()=>{state.selected=$('#part').value;const o=groups[state.mode].find(x=>x.name===state.selected);$('#part-info').textContent=o?o.label+' — '+(o.printed?'使用塑料耗材打印。':'购买现成金属标准件。'):'选择零件后，它会以亮色突出显示。';draw();};$('#explode').oninput=()=>{pause();state.e=+$('#explode').value;draw();};
$('#animate').onclick=()=>{if(state.playing){pause();return;}state.playing=true;$('#animate').textContent='暂停';$('#animate').setAttribute('aria-pressed','true');const start=performance.now();function tick(t){if(!state.playing)return;const f=Math.min((t-start)/7500,1);state.e=(1-Math.cos(f*2*Math.PI))/2;$('#explode').value=state.e;draw();if(f<1)requestAnimationFrame(tick);else pause();}requestAnimationFrame(tick);};
let drag=null;canvas.onpointerdown=e=>{drag=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(drag){state.yaw+=(e.clientX-drag[0])*.007;state.pitch+=(e.clientY-drag[1])*.007;drag=[e.clientX,e.clientY];draw();}};canvas.onpointerup=canvas.onpointercancel=()=>drag=null;canvas.onwheel=e=>{e.preventDefault();state.zoom=Math.max(.5,Math.min(3,state.zoom*Math.exp(-e.deltaY*.001)));draw();};canvas.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();state.yaw+=e.key==='ArrowLeft'?-.1:e.key==='ArrowRight'?.1:0;state.pitch+=e.key==='ArrowUp'?-.1:e.key==='ArrowDown'?.1:0;draw();};
const r=window.O11_RESULTS;$('#facts').innerHTML=[['独立接头 · 目标端点',r.targets-r.targetFailures+' / '+r.targets,'名义几何检查'],['两叉架 · 连续间隙','≥ '+r.clearance+' mm','α ±28°、β ±98°'],['胸肩布局 · 目标端点',r.bodyTargets-r.bodyFailures+' / '+r.bodyTargets,'所检刚体；不是整机放行']].map(x=>'<div class="fact">'+x[0]+'<strong>'+x[1]+'</strong><span>'+x[2]+'</span></div>').join('');$('#scope').textContent=r.bodyFailures?'胸肩仍有 '+r.bodyFailures+' 个端点出现干涉。本页小样用于独立材料实验；不要据此制作完整人偶。缺少线束、传感板、完整连接架及实物保持力验证。':'所检胸肩刚体端点未发现穿插。尚缺完整连接架、线束、传感板和实物材料性能，不能将此结果当作整机放行。';
addEventListener('resize',draw);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});tab('bench');window.O11_READY=true;window.O11_TEST={state,tab,draw};
})();
