'use strict';
(() => {
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],data=window.TUT_MODELS;
const state={tab:'design',version:'extended',alpha:0,beta:0,step:0,progress:0,playing:false,yaw:.61,pitch:1.05,zoom:1};
const reduced=matchMedia('(prefers-reduced-motion: reduce)'),canvas=$('#model');
const gl=canvas.getContext('webgl',{antialias:true,preserveDrawingBuffer:true});
const I=()=>[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];
const mul=(a,b)=>Array.from({length:16},(_,k)=>{const r=Math.floor(k/4),c=k%4;return [0,1,2,3].reduce((s,i)=>s+a[r*4+i]*b[i*4+c],0);});
function rotation(axis,a){const m=I(),c=Math.cos(a),s=Math.sin(a);if(axis==='x'){m[5]=c;m[6]=-s;m[9]=s;m[10]=c;}else if(axis==='z'){m[0]=c;m[1]=-s;m[4]=s;m[5]=c;}else{m[0]=c;m[2]=s;m[8]=-s;m[10]=c;}return m;}
function translate(x,y,z){const m=I();m[3]=x;m[7]=y;m[11]=z;return m;}
const colMajor=m=>new Float32Array(Array.from({length:16},(_,i)=>m[(i%4)*4+Math.floor(i/4)]));
const colors={C01:[.82,.52,.30],C02:[.29,.57,.47],C14:[.43,.56,.73],C15:[.53,.65,.80],metal:[.67,.69,.68],gauge:[.80,.73,.57]};
let program,loc,cache={};
if(gl){
 const shader=(type,src)=>{const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;};
 program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,'attribute vec3 p;attribute vec3 n;uniform mat4 M;uniform vec2 scale;varying vec3 normal;void main(){vec4 v=M*vec4(p,1.);normal=normalize((M*vec4(n,0.)).xyz);gl_Position=vec4(v.x*scale.x,v.y*scale.y,-v.z/200.,1.);}'));
 gl.attachShader(program,shader(gl.FRAGMENT_SHADER,'precision mediump float;varying vec3 normal;uniform vec3 color;void main(){vec3 n=normalize(normal);float l=.40+.60*max(0.,dot(n,normalize(vec3(-.3,.6,1.))));gl_FragColor=vec4(color*l,1.);}'));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));
 gl.useProgram(program);loc={p:gl.getAttribLocation(program,'p'),n:gl.getAttribLocation(program,'n'),M:gl.getUniformLocation(program,'M'),scale:gl.getUniformLocation(program,'scale'),color:gl.getUniformLocation(program,'color')};gl.enable(gl.DEPTH_TEST);
}else $('#webgl-error').hidden=false;
function mesh(key){if(cache[key])return cache[key];const o=data[key],a=[];for(const f of o.f){const [p,q,r]=f.map(i=>o.v[i]),u=q.map((v,i)=>v-p[i]),v=r.map((x,i)=>x-p[i]);let n=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]],l=Math.hypot(...n)||1;n=n.map(x=>x/l);for(const point of [p,q,r])a.push(...point,...n);}const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(a),gl.STATIC_DRAW);return cache[key]={b,count:a.length/6};}

function placed(){const a=state.alpha*Math.PI/180,b=state.beta*Math.PI/180,items=[];for(const n of ['C01','C02','C14','C15'])items.push({key:state.version+'_'+n,M:n==='C01'?I():n==='C02'?mul(rotation('x',a),rotation('y',b)):rotation('x',a),color:colors[n]});for(const key of Object.keys(data).filter(k=>k.startsWith('fastener_')))items.push({key,M:rotation('x',a),color:colors.metal});return {items,radius:33};}
function draw(){if(!gl||state.tab==='record')return;const w=canvas.clientWidth,h=canvas.clientHeight,dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(.906,.914,.875,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const {items,radius}=placed(),scale=Math.min(w,h)*.45/radius*state.zoom,view=mul(rotation('x',state.pitch),rotation('z',state.yaw));gl.uniform2f(loc.scale,2*scale/w,2*scale/h);
 for(const p of items){const o=mesh(p.key);gl.bindBuffer(gl.ARRAY_BUFFER,o.b);gl.enableVertexAttribArray(loc.p);gl.vertexAttribPointer(loc.p,3,gl.FLOAT,false,24,0);gl.enableVertexAttribArray(loc.n);gl.vertexAttribPointer(loc.n,3,gl.FLOAT,false,24,12);gl.uniformMatrix4fv(loc.M,false,colMajor(mul(view,p.M)));gl.uniform3fv(loc.color,p.color);gl.drawArrays(gl.TRIANGLES,0,o.count);}
}
let drag=null;canvas.onpointerdown=e=>{drag=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!drag)return;state.yaw+=(e.clientX-drag[0])*.009;state.pitch+=(e.clientY-drag[1])*.009;drag=[e.clientX,e.clientY];draw();};canvas.onpointerup=canvas.onpointercancel=()=>drag=null;canvas.onwheel=e=>{e.preventDefault();state.zoom=Math.min(2.5,Math.max(.5,state.zoom*Math.exp(-e.deltaY*.001)));draw();};canvas.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();if(e.key==='ArrowLeft')state.yaw-=.12;if(e.key==='ArrowRight')state.yaw+=.12;if(e.key==='ArrowUp')state.pitch+=.12;if(e.key==='ArrowDown')state.pitch-=.12;draw();};

const reports=window.O9_REPORTS,groups=reports.bounded_mapping.characters,map=$('#map'),ctx=map.getContext('2d');
function mapDraw(){ctx.clearRect(0,0,480,220);ctx.fillStyle='#edf0e5';ctx.fillRect(40,10,420,180);const x=b=>250+b*1.9,y=a=>100-a;ctx.fillStyle='#d1e4ca';ctx.fillRect(x(-100),y(30),380,60);ctx.strokeStyle='#6f9b63';ctx.strokeRect(x(-100),y(30),380,60);ctx.strokeStyle='#c0cbb9';ctx.beginPath();ctx.moveTo(40,y(0));ctx.lineTo(460,y(0));ctx.moveTo(x(0),10);ctx.lineTo(x(0),190);ctx.stroke();ctx.fillStyle='#516249';ctx.font='13px sans-serif';ctx.fillText('α',6,14);ctx.fillText('β',467,208);for(const a of [-75,-30,0,30,75])ctx.fillText(a+'°',3,y(a)+4);for(const b of [-100,-50,0,50,100])ctx.fillText(b+'°',x(b)-15,208);ctx.fillStyle=Math.abs(state.alpha)<=30.00001&&Math.abs(state.beta)<=100.00001?'#a16d2c':'#b64f3d';ctx.beginPath();ctx.arc(x(state.beta),y(state.alpha),5,0,Math.PI*2);ctx.fill();}
function update(){const a=state.alpha,b=state.beta;if(!state.pathMode)$('#angles').innerHTML=['φ','α','β','ψ'].map((n,k)=>'<div>'+n+'<b>'+([1,2].includes(k)?(k===1?a:b).toFixed(1)+'°':'—')+'</b></div>').join('');$('#alpha').value=a;$('#beta').value=b;$('#alpha-value').textContent=a.toFixed(1)+'°';$('#beta-value').textContent=b.toFixed(1)+'°';const box=$('#pose-result');box.className='status';$('#change-note').textContent=state.version==='extended'?'两只叉架各加长 3 mm；磁铁杯底部局部避让最多 0.35 mm，磁铁槽与轴颈保持。四件核心中立包络约 23 × 23 × 55 mm。':'上一轮的两只叉架各加长 2 mm，磁铁杯附近保持原始几何。四件核心中立包络约 23 × 23 × 53 mm。';
 if(Math.abs(a-75)<.01&&Math.abs(b-75)<.01){box.classList.add('bad');box.textContent='已保留的失败反例：这个范围外组合中，叉架仍会碰撞。不能把绿色工作区之外也当作可用。';}
 else if(state.version==='extended'&&Math.abs(a)<=30.00001&&Math.abs(b)<=100.00001){box.textContent='两只叉架：位于连续验证区间，名义间隙保守下界 ≥0.6 mm。实体限位和完整带线单臂仍待验证。';}
 else if(state.version==='original'&&Math.abs(a-15)<.01&&Math.abs(b-100)<.01){box.classList.add('warn');box.textContent='上一轮在这里没有名义穿透，但已找到约 0.443 mm 的间隙见证，达不到这轮采用的 0.6 mm 避让量。';}
 else{box.classList.add('warn');box.textContent='这里只作模型预览；此位置不在页面可引用的连续间隙证据内。不能由外观推断通过。';}mapDraw();draw();}
function pause(){state.playing=false;$('#play').textContent='▶ 播放路径';$('#play').setAttribute('aria-pressed','false');}
$$('[data-version]').forEach(b=>b.onclick=()=>{state.version=b.dataset.version;$$('[data-version]').forEach(v=>v.setAttribute('aria-pressed',String(v===b)));update();});
$('#preset').onchange=()=>{pause();state.pathMode=false;const q={neutral:[0,0],gap:[15,100],edge:[30,100],collision:[75,75]}[$('#preset').value];if(q){state.alpha=q[0];state.beta=q[1];update();}};
for(const id of ['alpha','beta'])$('#'+id).oninput=e=>{pause();state.pathMode=false;$('#preset').value='manual';state[id]=+e.target.value;update();};
$('#group').innerHTML=groups.map((g,i)=>'<option value="'+i+'">'+g.character+' · '+(g.side==='l'?'左侧':'右侧')+'</option>').join('');
function poseName(s){const named={neutral:'中立姿势',arms_forward:'双臂前伸',arms_overhead:'双臂举过头顶',arms_side:'双臂侧抬',hands_on_hips:'双手叉腰',arms_crossed:'双臂交叉（旧测试）',forehead:'手靠前额',palms_turn:'翻转手掌',arms_crossed_asymmetric_candidate:'双臂一高一低交叉'};if(named[s])return named[s];let m=s.match(/^([a-z]+)_[lr]\.([a-z]+)_(-?\d+)$/);if(m){const part={clavicle:'锁骨',upperarm:'上臂',elbow:'肘',forearm:'前臂',hand:'手腕'},action={protract:'前后移',elevate:'抬升',flex:'屈伸',abduct:'外展',twist:'转动',deviate:'侧偏'};return part[m[1]]+action[m[2]]+' '+m[3]+'°';}m=s.match(/^back_reach_(\d+)$/);if(m)return '向后伸手 '+m[1]+'°';m=s.match(/^(waist|chest)_(pitch|roll)_(-?\d+)_arm_side$/);if(m)return (m[1]==='waist'?'腰部':'胸部')+(m[2]==='pitch'?'前后倾':'侧倾')+' '+m[3]+'° · 手臂侧抬';return s;}
function setGroup(){pause();$('#path').innerHTML=groups[+$('#group').value].paths.map((p,i)=>'<option value="'+i+'">'+poseName(p.pose)+'</option>').join('');progress(0);}
function progress(value){state.pathMode=true;const p=groups[+$('#group').value].paths[+$('#path').value],v=value/100*(p.angles_deg.length-1),i=Math.floor(v),j=Math.min(i+1,p.angles_deg.length-1),f=v-i,q=p.angles_deg[i].map((x,k)=>x*(1-f)+p.angles_deg[j][k]*f);state.alpha=q[1];state.beta=q[2];state.progress=value;$('#progress').value=value;$('#percent').textContent=Math.round(value)+'%';$('#angles').innerHTML=['φ','α','β','ψ'].map((n,k)=>'<div>'+n+'<b>'+q[k].toFixed(1)+'°</b></div>').join('');$('#preset').value='manual';update();}
$('#group').onchange=setGroup;$('#path').onchange=()=>{pause();progress(0);};$('#progress').oninput=e=>{pause();progress(+e.target.value);};
$('#play').onclick=()=>{if(state.playing){pause();return;}if(state.progress>=100)progress(0);state.playing=true;$('#play').textContent='Ⅱ 暂停';$('#play').setAttribute('aria-pressed','true');let last=performance.now();function tick(now){if(!state.playing)return;const dt=Math.min(100,now-last);last=now;progress(Math.min(100,state.progress+dt/80));if(state.progress>=100)pause();else requestAnimationFrame(tick);}requestAnimationFrame(tick);};
const audit=reports.path_audit;$('#facts').innerHTML='<div class="fact">两叉架 · 连续区间<strong>≥ 0.6 mm</strong>α ±30° / β ±100°<small>采用完整网格与保守间隙界。不是已验证的制造公差。</small></div><div class="fact">原有目标 · 全部保留<strong>'+audit.total_retained_targets+' 个目标</strong>'+audit.sampled_rotations+' 个精确采样旋转；四角插值的最大已检查中点偏差约 '+audit.max_midpoint_rotation_deviation_deg.toFixed(3)+'°<small>未证明任意直接换姿或整臂不碰撞。</small></div><div class="fact">装配与工具 · 指定路径<strong>123 个位置</strong>四颗螺钉均有工作范围内的直工具接近姿态。<small>装配为离散检查；手柄与实际紧固力未验收。</small></div>';
$('#reset').onclick=()=>{state.yaw=.61;state.pitch=1.05;state.zoom=1;draw();};addEventListener('resize',draw);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});reduced.addEventListener('change',pause);setGroup();state.pathMode=false;$('#preset').value='neutral';state.alpha=0;state.beta=0;update();window.O9_READY=true;window.O9_STATE=state;
})();
